
spring:
  application:
    name: lastBlog
  datasource:
    url: jdbc:mysql://localhost:3306/blog_database?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源基本配置

    druid:
      # 数据源其他配置
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2 # log4j2
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        enabled: true
        url-pattern: "/*"
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        reset-enable: true # 启用HTML页面上的“Reset All”功能
        allow: "" # 设置IP白名单(没有配置或者为空，则允许所有访问)不设置部署到服务器会无法访问
      # deny: "" # 设置ip黑名单
      # 启用
      enable: true
swagger:
  enable: true

mybatis:
  type-aliases-package: com.finaldevelopment.YH.Entity
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8080
